Repository dnd-side-project/dnd-8th-6-frontend, pull requests merged in 2023-02, with the labels that each got.

#1 feat: tailwind 세팅, Text, Button, BottomNavigation, SettingContent 컴포넌트 작성
  package.json
  postcss.config.js
  src/components/BottomNavigation.tsx
  src/components/Button.tsx
  src/components/SettingContent.tsx
  src/components/Text.tsx
  src/pages/index.tsx
  src/styles/Home.module.css
  src/styles/globals.css
  tailwind.config.js
  yarn.lock
Labels: 🌟 feature

#2 fix: buttonText의 fontSize를 medium으로 변경
  src/components/Text.tsx
Labels: 🎨 style

#3 feat: next/font 적용
  src/pages/_app.tsx
  tailwind.config.js
Labels: 🌟 feature

#4 feat: tailwind custom color 적용
  tailwind.config.js
Labels: 🌟 feature

#6 feat: BottomNavigation 컴포넌트 작성
  src/components/BottomNavigation.tsx
Labels: 🌟 feature

#5 feat: Button 컴포넌트 작성
  src/components/Button.tsx
Labels: 🌟 feature

#7 feat: GitHubStats 컴포넌트 작성
  src/components/GitHubStats.tsx
  src/styles/globals.css
Labels: 🌟 feature

#8 feat: ToggleButton 컴포넌트 작성
  src/components/ToggleButton.tsx
Labels: 🌟 feature

#9 feat: 카카오 로그인 버튼 컴포넌트 작성
  .gitignore
  .idea/.gitignore
  .idea/dnd-8th-6-frontend.iml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/modules.xml
  .idea/vcs.xml
  declarations.d.ts
  next.config.js
  package-lock.json
  src/assets/github.svg
  src/assets/kakao.svg
  src/components/GithubButton.tsx
  src/components/KakaoButton.tsx
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/index.tsx
  src/pages/login.tsx
  src/styles/globals.css
Labels: 👷 chore

#10 fix: eslint, prettier 적용 에러 해결
  package-lock.json
  package.json
  src/components/GithubButton.tsx
  src/components/KakaoButton.tsx
  src/pages/login.tsx
Labels: 👷 chore, 🔪 fix

#11 feat: User 컴포넌트 작성
  next.config.js
  src/assets/star.svg
  src/components/GithubButton.tsx
  src/components/KakaoButton.tsx
  src/components/User.tsx
  src/pages/login.tsx
  yarn.lock
Labels: 🌟 feature
